# Generated by Django 3.0.7 on 2020-06-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_movie_taile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_taile',
            new_name='movie_trailer',
        ),
    ]
