# Generated by Django 3.0.7 on 2020-06-12 15:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20200612_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 15, 24, 56, 18605, tzinfo=utc)),
        ),
    ]
